### ISSUE TITLE
Using Irrlicht engine and "IrrAssimp" to import the FBX file can not be normal display skeletal animation

### ISSUE THREAD

**Issue by pengshiping** [JLouis-B/IrrAssimp#3] opened 2015-08-31 09:19 UTC
Hi:
I tried to use IrrAssimp to load the FBX file, but I use your code, the FBX model file that contains skeletal animation can not be display, you can help me solve this problem?
My email is: pengshiping@163.com, thank you.

**Comment by vinjn** [comment] 2015-08-31 12:34
Please upload the problematic FBX file for the JLouis to repro the bug.

**Comment by pengshiping** [comment] 2015-09-01 08:28
But not upload FBX file，Can you contact JLouis？

**Comment by pengshiping** [comment] 2015-09-01 08:31
原来你也国内的，你也在使用IrrAssimp的代码吗？你有没有遇到这个问题？

**Comment by JLouis-B** [comment] 2015-09-01 10:32
Hi,
I have well received your mails with the files.
I will check this.

**Comment by JLouis-B** [comment] 2015-09-06 17:07
I think that I have identified what is the problem, but it's not very easy to fix yet.

For the technical details :
Assimp doesn't give the skeleton at bind pose but at frame 1 with the boneOffset matrix (mesh space to bone space) that I use to compute the bind pose.
The problem is when a bone has no influence on the mesh, I don't have the boneOffset to compute the bind pose of the bone and it has a wrong R/T/S matrix.

So compute the bind pose of the skeleton is not the good approach and it's a cause of bugs.
The problem is that Assimp just give a boneOffset matrix that I can't use directly with Irrlicht.

I probably should try to make an other branch where I use boneOffset to manually skin the mesh at frame 1 with the boneOffset (lose bind pose and a bit longer, but it should fix the skeleton problems)

While waiting for, a potential workaround, when I import your fbx in Blender and I re-export it in fbx, it works.
Edit : Not sure, but you can also try to keyframe all your bones (with also the bones that you don't use in the animation) on at least one keyframe can potentially fix this bug.

**Comment by JLouis-B** [comment] 2015-09-11 21:16
Fixed in the BonesSkinning branch.

**Comment by vinjn** [comment] 2015-09-12 01:57
Cool, you can also add `Fix #3` in the change list description to let Github automatically mark this issue as fixed.

**Closed as completed** 2015-09-23 12:29 UTC
